<a href="https://colab.research.google.com/github/ResponsiveWebApps/YahooFinData/blob/master/yahoo_fin.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Imports**

In [1]:
# import stock_info module from yahoo_fin
!pip install yahoo-fin
!pip install requests_html
from yahoo_fin import stock_info as si

Requirement already satisfied: yahoo-fin in /usr/local/lib/python3.6/dist-packages (0.8.6)
Requirement already satisfied: requests_html in /usr/local/lib/python3.6/dist-packages (0.10.0)
Requirement already satisfied: parse in /usr/local/lib/python3.6/dist-packages (from requests_html) (1.18.0)
Requirement already satisfied: pyppeteer>=0.0.14 in /usr/local/lib/python3.6/dist-packages (from requests_html) (0.2.2)
Requirement already satisfied: bs4 in /usr/local/lib/python3.6/dist-packages (from requests_html) (0.0.1)
Requirement already satisfied: w3lib in /usr/local/lib/python3.6/dist-packages (from requests_html) (1.22.0)
Requirement already satisfied: fake-useragent in /usr/local/lib/python3.6/dist-packages (from requests_html) (0.1.11)
Requirement already satisfied: pyquery in /usr/local/lib/python3.6/dist-packages (from requests_html) (1.4.1)
Requirement already satisfied: requests in /usr/local/lib/python3.6/dist-packages (from requests_html) (2.23.0)
Requirement already satisfied: appdirs<2.0.0,>=1.4.3 in /usr/local/lib/python3.6/dist-packages (from pyppeteer>=0.0.14->requests_html) (1.4.4)
Requirement already satisfied: tqdm<5.0.0,>=4.42.1 in /usr/local/lib/python3.6/dist-packages (from pyppeteer>=0.0.14->requests_html) (4.49.0)
Requirement already satisfied: pyee<8.0.0,>=7.0.1 in /usr/local/lib/python3.6/dist-packages (from pyppeteer>=0.0.14->requests_html) (7.0.4)
Collecting urllib3<2.0.0,>=1.25.8
  Downloading https://files.pythonhosted.org/packages/9f/f0/a391d1463ebb1b233795cabfc0ef38d3db4442339de68f847026199e69d7/urllib3-1.25.10-py2.py3-none-any.whl (127kB)
     |████████████████████████████████| 133kB 4.4MB/s
Requirement already satisfied: websockets<9.0,>=8.1 in /usr/local/lib/python3.6/dist-packages (from pyppeteer>=0.0.14->requests_html) (8.1)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.6/dist-packages (from bs4->requests_html) (4.6.3)
Requirement already satisfied: six>=1.4.1 in /usr/local/lib/python3.6/dist-packages (from w3lib->requests_html) (1.15.0)
Requirement already satisfied: lxml>=2.1 in /usr/local/lib/python3.6/dist-packages (from pyquery->requests_html) (4.2.6)
Requirement already satisfied: cssselect>0.7.9 in /usr/local/lib/python3.6/dist-packages (from pyquery->requests_html) (1.1.0)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests->requests_html) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests->requests_html) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests->requests_html) (2020.6.20)
ERROR: kaggle 1.5.8 has requirement urllib3<1.25,>=1.21.1, but you'll have urllib3 1.25.10 which is incompatible.
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
Installing collected packages: urllib3
  Found existing installation: urllib3 1.24.3
    Uninstalling urllib3-1.24.3:
      Successfully uninstalled urllib3-1.24.3
Successfully installed urllib3-1.25.10

**S&P 500 Data**

In [23]:
print("S&P 500 Recent Price: " + str(si.get_live_price('spy')))

si.get_quote_table("spy", dict_result = False)

S&P 500 Recent Price: 330.29998779296875

                 attribute            value
0            52 Week Range  218.26 - 358.75
1                      Ask    331.02 x 1400
2              Avg. Volume      7.05777e+07
3        Beta (5Y Monthly)                1
4                      Bid     331.06 x 900
5              Day's Range  325.86 - 330.90
6      Expense Ratio (net)            0.09%
7           Inception Date       1993-01-22
8                      NAV           326.95
9               Net Assets          274.45B
10                    Open           328.57
11          PE Ratio (TTM)              NaN
12          Previous Close           326.97
13             Quote Price            330.3
14                  Volume      6.36121e+07
15  YTD Daily Total Return            3.01%
16                   Yield            1.85%

**Biggest gainers**

In [28]:
si.get_day_gainers()

   Symbol                                   Name  ...  Market Cap  PE Ratio (TTM)
0    CVNA                            Carvana Co.  ...  3.8705e+10             NaN
1   NWITY     Network International Holdings plc  ...   2.065e+09            0.22
2    FROG                             JFrog Ltd.  ...   6.893e+09             NaN
3     VRM                            Vroom, Inc.  ...   6.356e+09             NaN
4    BPMC        Blueprint Medicines Corporation  ...   4.824e+09             NaN
..    ...                                    ...  ...         ...             ...
95  BBVXF  Banco Bilbao Vizcaya Argentaria, S.A.  ...  1.6943e+10            3.53
96    ZTO              ZTO Express (Cayman) Inc.  ...  2.3407e+10           33.33
97   STRA              Strategic Education, Inc.  ...   2.299e+09           18.15
98    LEN                     Lennar Corporation  ...  2.4333e+10           11.15
99   YETI                    YETI Holdings, Inc.  ...   4.093e+09           60.23

[100 rows x 9 columns]

**Top Cryptocurrencies**

In [30]:
si.get_top_crypto()

      Symbol  ... Circulating Supply
0    BTC-USD  ...         1.8498e+07
1    ETH-USD  ...        1.12721e+08
2   USDT-USD  ...         1.5205e+10
3    XRP-USD  ...         4.5097e+10
4    BCH-USD  ...         1.8525e+07
..       ...  ...                ...
87  NEBL-USD  ...         1.6399e+07
88  TAAS-USD  ...          8.146e+06
89  GAME-USD  ...         9.7604e+07
90  VERI-USD  ...           2.15e+06
91   DNT-USD  ...              6e+08

[92 rows x 10 columns]